name: Crawl Jobs

on:
  workflow_dispatch:   # 수동 / API 트리거 가능
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 (UTC 기준)

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # GitHub Actions가 commit/push 할 수 있도록 권한 부여

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 보안상 권장

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Run crawler
        run: |
          python src/run_all.py
          python normalize_jobs.py ./json

      - name: 💾 Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          git add normalized/ json/
          git commit -m "🔄 Update jobs $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push

      - name: 🔥 Update Firebase status (optional)
        if: env.FIREBASE_TOKEN != ''
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "✅ Crawl completed"
